[server]
headless = false
port = 8505
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#2563eb"
backgroundColor = "#f1f5f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "inter"
